### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Chirag-Mathur** [Chirag-Mathur/code-world#44]
Add CONTRIBUTING.md file link to the existing readme.

**Comment by gaurangisinha** [comment]
Hello @Chirag-Mathur Could I contribute and update the readme? I will be grateful

**Comment by Chirag-Mathur** [comment]
Ya sure @gaurangisinha 👍

**Comment by priyanshupardhi** [comment]
Hey, @Chirag-Mathur can I work on it?

**Comment by priyanshupardhi** [comment]
@Chirag-Mathur Do I need to write the entire Contribution guideline sentence or just add the link

**Comment by Chirag-Mathur** [comment]
@priyanshupardhi I have assigned it to @gaurangisinha , If not completed within a day, I will assign it to you.

**Comment by priyanshupardhi** [comment]
@Chirag-Mathur any update ?
